use std::path::PathBuf;

pub enum SettingsInteraction {
    None,
    ThemeSelected(String),
    AddSongDirectory,
    RemoveSongDirectory(usize),
    AddSoundFontFolder,
    RemoveSoundFontFolder(usize),
    SoundFontSelected(usize),
    InputDeviceSelected(String),
    OutputDeviceSelected(String),
    AudioGainChanged(f32),
    PlaybackGainChanged(f32),
    PianoRangeStartChanged(u8),
    PianoRangeEndChanged(u8),
    VerticalGuidelinesToggled(bool),
    HorizontalGuidelinesToggled(bool),
    GlowToggled(bool),
    NoteLabelsToggled(bool),
    SeparateChannelsToggled(bool),
    VelocityEnabledToggled(bool),
    VelocityMinChanged(f32),
    VelocityMaxChanged(f32),
    PlayNote(u8, u8),
    StopNote(u8),
    ResetToDefaults,
    SaveChanges,
    Back,
    OpenPopup(String),
}
